NHSDigital/nhs-login-help-centre

- jsconfig.json
- src/_includes/footer.njk
- src/_includes/head.njk
- src/contact-error.njk
- src/contact-sent.njk
- src/contact-unavailable.njk
- src/contact.njk
- src/css/form.css
- src/js/contact-page.js
- src/js/form-builder.js
- src/js/header-marker.js
- src/js/time.js
- src/js/utils.js
- src/js/validators.js
- src/manage/delete.md
- src/search/index.njk
> Release 86.1

- src/mixedsupport.md
- src/provewhoyouare/withid.md
- src/provewhoyouare/withoutid.md
Content updates for prove who you are with photo ID, CID7003, CID7023 articles.
> CID-8744 Content changes

- lib/article.js
- src/_data/environment.js
- src/contact.njk
- src/js/contact-page.js
removing drop down for error codes, this MR means it should be automatically filled where possible instead.
> removing error code drop down

- .eleventy.js
- src/js/search.js
- src/search/data-set.njk
> CID-11496 move search data files so they aren't treated as html pages

- src/mixedsupport.md
- src/provewhoyouare/withoutid.md
Changes included;
- CID-11608 - Update mixed reference POL articles
> Merge develop into master

- src/manage/emailaddresses.md
- src/provewhoyouare/index.md
- src/provewhoyouare/withid.md
- src/provewhoyouare/withoutid.md
- src/recordvideo.md
Simple content update to replace I.D. with ID plus add aria-label for accessibility purposes.
> Cid 11587 - replace I.D. with ID

- src/provewhoyouare/withid.md
- src/provewhoyouare/withoutid.md
- replace forms of ID with other accepted ID on the WithID page
- Add missing full stop
> CID-11834 - Other accepted ID

- gulpfile.js
- package-lock.json
- package.json
Add hash output for inline scripts : these are consumed later to construct﻿ the Content Security Policy.
> Add hashing for scripts

- src/_data/clients.json
- src/manage/delete.md
Merge to master looked like it was pulling some older tickets too, but checked with Lydia and these were fine, develop and master look to have got a bit odd after last merge
> Merge CID-13767 to Master

- src/_data/clients.json
> CID-13802 Merge to Master

- src/manage/phonenumber.md
Merge to Master for CID-12150 - Removing reference to CID3001
> Merge to Master for CID-12150 - Removing reference to CID3001

- src/_data/clients.json
- src/setupnhslogin.md
CID-14443 - Add client friendly name for Netcall
> CID-14443 - Add client friendly name for Netcall

- src/_data/clients.json
CID-14589 - Add OXDH to Help Centre Form
> CID-14589 - Add OXDH to Help Centre Form

- src/_data/clients.json
> CID-15409 (#169)

- src/_data/clients.json
CID-15508 - New 'Anima for Patients' partner
> CID-15508 - New 'Anima for Patients' partner

- src/_data/clients.json
CID-15652 - Omron added to Help Centre dropdown as "Viso"
> CID-15652 - Omron added to Help Centre dropdown as "Viso"

- src/_data/clients.json
Here's a link to the ticket: [CID-15608](https://nhsd-jira.digital.nhs.uk/browse/CID-15608)
> CID-15608 add a new partner to the contact form - Alder Hey @nywhere

- src/_data/clients.json
Here's the link to the ticket: [CID-15630](https://nhsd-jira.digital.nhs.uk/browse/CID-15630)
> CID-15630 remove partner from contact help center dropdown - Doctorlink App

- src/contact.njk
Ticket link: [CID-15655](https://nhsd-jira.digital.nhs.uk/browse/CID-15655)
> CID-15655 update texts on the help center contact page

- src/_data/clients.json
[CID-15674](https://nhsd-jira.digital.nhs.uk/browse/CID-15674)
> CID-15674: add 'Kent & Medway Patient Portal' to client list

- src/manage/devices.md
Link to ticket: [CID15741](https://nhsd-jira.digital.nhs.uk/browse/CID-15741)
This PR amends the 'Remember Device' section of the Help center page to correctly instruct a user on removing a remembered device.
> CID-15741 amend content on the remembered device page

- src/morethanoneaccount.md
CID-15771 more than one account page
> CID-15771 (#190)

- src/morethanoneaccount.md
> CID-15793 - Duplicate account content update

- src/manage/nhs-record-contact-details.md
[CID-15512](https://nhsd-jira.digital.nhs.uk/browse/CID-15512)
> CID-15512: Help center - 'Manage NHS Record - NHS record contact details' article update

- src/js/validators.js
- updated email regex to use spa-login email regex
> CID-16215: improve email validation in contact us form

- .eleventy.js
- README.md
- lib/article.js
- package-lock.json
- package.json
- Upgraded Eleventy to 2.0.1
- Fixed all breaking changes
- Force install the version of some transitive dependencies
> Cid 16764 - upgrade Eleventy to version 2

- src/_data/clients.json
[CID-16970](https://nhsd-jira.digital.nhs.uk/browse/CID-16970)
> CID-16970: Add Cohesion Medical Ltd to Help Centre dropdown

- src/_data/clients.json
Proxy Application Service to be added on ZenDesk & Help Centre dropdown as "Apply for access to another patient's GP services"
> CID-17227 - Proxy Application Service to be added

- .eleventy.js
- README.md
- lib/article.js
- src/morethanoneaccount.njk
* Added njk file functionality to contactUsLinks
* removed weird formatting
* Updated readme, added default values for desc/code
* Changed error description to match tab title
* undo docs path change
* refactor resolving contact us links
* handle multiple error codes / descriptions for the same page
* handle missing 'errors' key in article-njk front matter
---------
> CID-16848: Fix Duplicate account tickets description (#245)

- src/_data/clients.json
CID-18197 better client added to dropdown
> CID-18197 (#258)

- src/contact-sent.njk
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-18091
This PR corresponds to the CID-18091 JIRA ticket. It updates contents of the Message Sent page.
> CID-18091: updated contact-sent page

- src/_data/clients.json
CID-18548 new client in dropdown menu
> CID-18548 - Add Aseptika Ltd Partner to the HC Contact Us Form

- src/contact.njk
- src/js/contact-page.js
- src/js/validators.js
**Description:**
This PR corresponds to [CID-18090 ](https://nhsd-jira.digital.nhs.uk/browse/CID-18090)JIRA ticket. It updates the help centre [Contact Us form](https://help.dev.signin.nhs.uk/contact). 
**For Reviewers:**
All Help Centre environments point to Live ZenDesk, so submitting a contact form will result in a real ticket being raised.  To avoid sending test entries into Live it's possible to test the contact form by entering a specific line of text in the Message field.  In ZenDesk this will be recognised as coming from a test and will then auto close the entry and respond to the users email. The message to enter in the Describe the problem field should be: 
"Contact Us Form submitted for NHS login regression test"
> CID-18090: update contact form

- .eleventy.js
- src/_data/clients.json
- src/js/contact-page.js
> Help Centre Contact Us Form Changes

- src/manage/delete.md
> CID-18311 (#274)

- src/_data/clients.json
[CID-18918](https://nhsd-jira.digital.nhs.uk/browse/CID-18918)
> CID-18918: add 'Virtual Lucy' to help centre dropdown

- src/_data/clients.json
[CID-18777](https://nhsd-jira.digital.nhs.uk/browse/CID-18777)
> CID-18777: update Lloyds in help centre dropdown

- src/_data/clients.json
[CID-18984](https://nhsd-jira.digital.nhs.uk/browse/CID-18984)
> CID-18984: remove NHS COVID Pass from contact us dropdown

- src/_data/clients.json
added Devon Diabetic Eye Screening Patient Portal
> CID-19184 and CID-18935 update contact us client dropdown

- src/_data/clients.json
> CID-19267 (#288)

- src/_data/clients.json
[CID-19897](https://nhsd-jira.digital.nhs.uk/browse/CID-19897)
> CID-19897: add PatientAide to client list

- .eleventy.js
- src/_includes/breadcrumbs.njk
> CID-19856 Breadcrumbs fix (#307)

- src/provewhoyouare/withid.md
[CID-20175](https://nhsd-jira.digital.nhs.uk/browse/CID-20175)
> CID-20175 Update help and support to reflect ID checker wait times

- src/provewhoyouare/withid.md
Jira ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-20221
> CID-20221: updated PYI accepted documents

- src/_data/clients.json
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-21110
> CID-21110: Adding NowPatient to the clients list

- src/_data/clients.json
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-21066
> CID-21066: Adding Check My Record to the clients list

- src/_data/clients.json
**Ticket:** https://nhsd-jira.digital.nhs.uk/browse/CID-20649
> CID-20649: Removing Patient Pack from the clients list

- src/manage/emailaddresses.md
Prototype link: https://prototype-nhs-login-help-87153c4cb7ee.herokuapp.com/manage/email/article
> CID-20976 - FE content update - email address page

- src/_data/clients.json
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-21539
> CID-21539: Adding Gro Health to clients list

- src/_data/clients.json
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-21451
> CID-21451: Adding Beth to clients list

- src/_data/clients.json
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-21432
> CID-21432: Removing NHS WISH from clients list

- src/_data/clients.json
Ticket: https://nhsd-jira.digital.nhs.uk/browse/CID-21343
> CID-21343: Adding BSMHFT Patient Portal to clients list
